services:
  app:
    build:
      context: app/
      dockerfile: Dockerfile-app
      args:
        APP_PORT: "8080"
    container_name: app
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - APP_PORT=8080
    volumes:
      - ./app/project:/app/project
      - ./db:/app/db

  etl:
    build:
      context: etl/
      dockerfile: Dockerfile-etl
    container_name: etl
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - ./gpx/data:/app/data  # raw data in local disk
      - ./etl/lib:/app/lib
      - ./etl/history:/app/history
