# Generated by Django 5.1.6 on 2025-02-13 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_add_initial_userpoi_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('segment', models.SmallIntegerField()),
                ('state', models.CharField(max_length=20)),
                ('start_segment', models.DateTimeField()),
                ('last_timestamp_utc', models.DateTimeField()),
                ('retrieved_at_utc', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['start_segment'],
                'indexes': [models.Index(fields=['name'], name='idx_name'), models.Index(fields=['start_segment'], name='idx_start_segment'), models.Index(fields=['last_timestamp_utc'], name='idx_last_timestamp_utc')],
                'unique_together': {('uuid', 'last_timestamp_utc')},
            },
        ),
    ]
