# Generated by Django 5.1.6 on 2025-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0003_tilesegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilesegment',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
