# Generated by Django 5.1.6 on 2025-02-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_alter_tilesegment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoi',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userpoi',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userpoi',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
