FROM python:3.11-bullseye

WORKDIR /app

# AWS CLI
ENV PATH="/root/.aws-cli/bin:$PATH"

RUN apt-get update && \
    apt-get install -y curl zip unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip && \
    rm -rf /var/lib/apt/lists/*

RUN aws --version

COPY requirements-layer.txt version.txt upload.sh lambda_runner.py .

RUN chmod 744 ./upload.sh
