# Runs flake8 on changed projects in the repository.

on: [push]

jobs:
  list-changed-directories:
    runs-on: ubuntu-latest
    outputs:
      changed-projects: ${{ steps.list-changed-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get project names of changed files
        id: list-changed-projects
        if: github.ref != 'refs/heads/main'
        run: |
          git fetch origin main
          git branch --track main origin/main
          changed_dirs=$(git diff origin/main --name-only | cut -d/ -f1 | sort -u | grep -v '^.github')
          echo "Changed directories: $changed_dirs"
          if [[ -z "$changed_dirs" ]]; then 
            echo "No changed projects found."
            echo "projects=[]" >> $GITHUB_OUTPUT
          else
            project_json=$(echo "$changed_dirs" | jq -R . | jq -s . | jq -c .)
            echo "Changed dirs: $project_json"
            echo "projects=$project_json" >> $GITHUB_OUTPUT
          fi
  lint:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: list-changed-directories
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-changed-directories.outputs.changed-projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies and run linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          echo "Running flake8..."
          flake8 --version
          cd ${{ matrix.dir }}
          flake8 . --count --max-line-length=150 --statistics
          echo "Done linting."
